### ISSUE TITLE
does the code wrong or the data file corrupt?

### ISSUE THREAD

**Issue by SeekPoint** [badripatro/PQG#2]
ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/PQG/prepro$ python quora_prepro.py
Traceback (most recent call last):
  File "quora_prepro.py", line 80, in <module>
    main()
  File "quora_prepro.py", line 16, in main
    if row[5]=='0' and row[4][-1:]=='?':#the 6th entry in every row has value 0 or 1 and it represents paraphrases if that value is 1
IndexError: list index out of range
ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/PQG/prepro$

**Comment by ixn872** [comment]
Hi! 

Instead of ',' comma separator use '/' tab separator a few lines above line 16 on file quora_prepro.py!
