### ISSUE TITLE
How to generate new paraphrases

### ISSUE THREAD

**Issue by thefirebanks** [badripatro/PQG#5]
Hello! 

I truly appreciate the well documented code and pre-trained model - I was wondering, how would I use the pretrained model to generate paraphrases based on new data? As in, how should I input sentences to the model? Thanks!

**Comment by badripatro** [comment]
In order to generate paraphrase of our dataset, firstly, use the word embedding of the pre-trained PQG model and then extract encode feature of the input and then pass the encoding feature to the decoder to generate the deserve paraphrase.
